// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Api.LeaseSchedule.LeaseScheduleDetailDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeaseSchedules");
                });

            modelBuilder.Entity("Api.LeaseSchedule.ScheduleEntryDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaseScheduleDetailDtoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseTerm")
                        .HasColumnType("TEXT");

                    b.Property<string>("LesseeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaseScheduleDetailDtoId");

                    b.ToTable("ScheduleEntryDto");
                });

            modelBuilder.Entity("Api.LeaseSchedule.ScheduleEntryDto", b =>
                {
                    b.HasOne("Api.LeaseSchedule.LeaseScheduleDetailDto", null)
                        .WithMany("ScheduleEntry")
                        .HasForeignKey("LeaseScheduleDetailDtoId");
                });
#pragma warning restore 612, 618
        }
    }
}
